### ISSUE TITLE
[Question]: posit webshot2 as phantomjs webshot replacement - ideal/pcaExplorer 

### ISSUE THREAD

**Issue by tamuanand** [federicomarini/ideal_serveredition#10]
Hi @federicomarini 

I have a question on PhantomJS requirements for ideal and pcaExplorer. https://federicomarini.github.io/ideal/articles/ideal-usersguide.html#report-editor says

```
please install the PhantomJS executable before launching the app.
This can be done by using the [webshot](https://cran.r-project.org/package=webshot) package 
and calling [webshot::install_phantomjs()](http://wch.github.io/webshot/reference/install_phantomjs.html) - 
HTML widgets will be rendered automatically as screenshots
```

As you might be aware,development on PhantomJS was suspended 5 years ago: https://github.com/ariya/phantomjs/issues/15344

Given the above, Posit team has created webshot2 to solve the PhantomJS issue: https://github.com/rstudio/webshot2

Would it be possible to update pcaExplorer/ideal to rely on webshot2 

Thanks in advance.

**Comment by federicomarini** [comment]
Good point, I'll have a look at that as soon there is bandwidth to inspect how a new version would do that!
Thanks for the suggestion - will probably refer anyway to the original https://github.com/federicomarini/ideal repo

**Comment by federicomarini** [comment]
Ok, from some searches I think the situation is as it follows:
* phantomJS is archived, but still seems to work pretty fine
* webshot, using phantomJS, is alive and running, so there is no need to explicitly kick it out
* actually, the static tables are created without specifying any behavior, so I guess it is how DT decides to create the snapshot, rather than me telling the users to install/use either package

I can refer to webshot2 being available in the documentation, maybe it is simply a proactive measure in case DT changes the way it works under the hood.

Would that be a good compromise?

**Comment by tamuanand** [comment]
Hi @federicomarini 

I know it depends on your bandwidth - given that websot2 is developed by Rstudio/posit and will be maintained, IMHO it might be better to update ideal/pcaExplorer with webshot2 - but I leave that to you. 

That will be good. 
> I can refer to webshot2 being available in the documentation, maybe it is simply a proactive measure in case DT changes the way it works under the hood. Would that be a good compromise

Once again - thanks a lot for the absolutely great tools.

**Comment by federicomarini** [comment]
As I said - I cannot really control how DT chooses to export the static versions of the interactive tables. This is likely a fallback solution designed and implemented in the DT package 😉 

So, well, there's not too much I can do about that.

I am happy you enjoy the tools!
