### ISSUE TITLE
Bug in the sever edition but not in local version

### ISSUE THREAD

**Issue by Hoohm** [federicomarini/ideal_serveredition#2]
Hello and thanks for creating this.

I'm currently running ideal on a shiny server via docker and I have some bugs that I only have on the server edition.

An example would be gene ids not showing up properly on the dropdown menu on the left using the server version but this works on the local version.

Are the two the same or do you have some fixes in the local version that are not found in the server edition?

Best wishes

**Comment by federicomarini** [comment]
Hi Patrick,

I need to update the repo to the current solution I switched to, which is better on many levels:

- no need to reupdate the server repo
- only reupdate the package itself

I'll mirror the setup I am using on the server I am managing, where this is already in use.

Re: the behavior you describe. I recall having it for a while, but could not pinpoint exactly what the reason was.

Anyway: please stay tuned 😉

**Comment by federicomarini** [comment]
@Hoohm: the new configuration should be available after f08d735cea8d8ab7b6037dae0cf965b4b3a72942

What went on under the hood: unneeded code duplication is gone, the app can (and should) be called with the two lines in `app.R`.

Please let me know if the problem persists.
Keep in mind you might need to remove/rename the existing `server.R` and `ui.R` - but this also gives you the newest version automatically (simply when updating the package globally).

**Comment by Hoohm** [comment]
@federicomarini thanks for the update.

I'm building the docker image again and let you know if it works.

Once it runs properly, I'll push the Dockerfile on my github if you want to use it as well.
I just started using docker yesterday so it's probably not the perfect way of doing it, but if it runs, I'm happy with it.

**Comment by Hoohm** [comment]
@federicomarini The app works as it is supposed to.

I still have the issue I mentioned before. I'm opening this on the main ideal issues.
