### ISSUE TITLE
Question: How to have only select organisms in the annotation list pulldown

### ISSUE THREAD

**Issue by tamuanand** [federicomarini/ideal_serveredition#4]
Hello @federicomarini 

Thanks a lot for this wonderful tool (and pcaExplorer) -- bigger thanks for making available the shiny editions in both,

When creating the Optional step for annotation data frame - there is this pulldown of species (Anopheles, Arabidopsis, ... to Worm, Yeast, Zebrafish".

Question: If I need to prune this list and have only select species, how do I do it?  Say I need only Bovine, Canine, Chicken - here all do I need to make these changes?

Thanks in advance

**Comment by federicomarini** [comment]
Hey there @tamuanand,

the part that handles this control is in these lines from the main app of `ideal` itself: https://github.com/federicomarini/ideal/blob/9bc18165a0692a7300292b57dc2dc7291da961c1/R/ideal.R#L1554-L1590

I never had the need to prune it in advance since the autocompletion functionality helps "enough" the user to highlight and select the corresponding objects.

If you want to basically subset the data frame as specified in the lines above, that should do it!
HTH,
Federico

**Comment by tamuanand** [comment]
Hi @federicomarini 

That helps a lot. I think I will close this issue.

I have some open issues on pcaExploer_serveredition GH  - If you prefer, I can email or keep adding to GH

Thanks

**Comment by federicomarini** [comment]
Got it, I'll catch up directly there 😉
